config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'notifications#new'
  post '/create', to: 'notifications#create', as: 'notify'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def new; end

  def create
    NotifierJob.perform_later(notification_params)
    redirect_to root_path
  end

  private

  def notification_params
    { to: params[:to], subject: params[:subject], body: params[:body] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Example2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notifications/new.erb
<%= form_tag(notify_path, method: :post) do %>
  <p>
    <%= label_tag(:to, 'Recipient') %>
    <%= text_field_tag(:to, nil, type: :'email') %>
  </p>
  <p>
    <%= label_tag(:subject, 'Subject') %>
    <%= text_field_tag(:subject, nil, type: :'text') %>
  </p>
  <p>
    <%= label_tag(:body, 'Body') %>
    <%= text_area_tag(:body) %>
  </p>
  <p>
    <%= submit_tag('Submit') %>
  </p>
<% end %>